# Generated by Django 3.2.8 on 2021-10-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datakeys',
        ),
    ]
