# Generated by Django 3.2.8 on 2021-10-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocencryption', '0002_alter_datakeys_data_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakeys',
            name='data_key',
            field=models.BinaryField(),
        ),
    ]
